(self.AMP=self.AMP||[]).push({n:"amp-form",v:"1906111828200",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function n(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Qa=b.prototype};function ha(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ia(a){return new Promise(function(b){b(a())})}function ja(){var a,b,c;this.sa=new Promise(function(a,d){b=a;c=d});this.Ia=b;this.Ha=c;this.ga=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}ja.prototype.add=function(a){var b=this,c=++this.ga;Promise.resolve(a).then(function(a){b.ga===c&&b.Ia(a)},function(a){b.ga===c&&b.Ha(a)});return this.sa};
ja.prototype.then=function(a,b){return this.sa.then(a,b)};function ka(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ma(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2],c[2]):"";b[d]=e}return b};var na="";
function p(){var a,b=a||self;if(b.AMP_MODE)var c=b.AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=c.__karma__&&c.__karma__.config.amp.testOnIe,g=ma(c.location.originalHash||c.location.hash);d=d.spt;var h=ma(c.location.search);na||(na=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011906111828200");c=b.AMP_MODE={localDev:!1,development:!("1"!=g.development&&!c.AMP_DEV_MODE),examiner:"2"==g.development,filter:g.filter,geoOverride:g["amp-geo"],userLocationOverride:g["amp-user-location"],minified:!0,
lite:void 0!=h.amp_lite,test:e,testIe:f,log:g.log,version:"1906111828200",rtvVersion:na,singlePassType:d}}return c};var oa=Object.prototype.toString;function pa(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var q=self.log;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user}function qa(){if(q.dev)return q.dev;throw Error("failed to call initLogConstructor");}function t(a,b,c,d){r().assert(a,b,c,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function u(a,b){var c,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(ra(d,b)){var f=v(d,b);if(f)return f}if(!c)return null}a=w(a);a=x(a);return ra(a,b)?v(a,b):null}function z(a,b){a=a.__AMP_TOP||a;return v(a,b)}function A(a,b){var c=w(a);c=x(c);return v(c,b)}function sa(a,b){return ta(x(a),b)}function w(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function x(a){a=w(a);return a.isSingleDoc()?a.win:a}
function v(a,b){ra(a,b);var c=ua(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function va(a,b){var c=ta(a,b);if(c)return c;a=ua(a);a[b]=wa();return a[b].promise}function ta(a,b){var c=ua(a)[b];if(c){if(c.promise)return c.promise;v(a,b);return c.promise=Promise.resolve(c.obj)}return null}function ua(a){var b=a.services;b||(b=a.services={});return b}function ra(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}
function wa(){var a=new ha,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var xa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function ya(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};var za;var Aa=Object.prototype.hasOwnProperty;function B(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function C(a){return a||{}}
function Ba(a,b){var c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.G=b.t;a.B=b.s;a.V=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.G!==a.B&&(a.V>c?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(Aa.call(a.G,b)){var d=a.G[b];if("[object Object]"===oa.call(c)&&"[object Object]"===oa.call(d)){e.push({t:d,s:c,d:a.V+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,V:a.V}}}
;function Ca(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function Da(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function Ea(a){var b="fieldset";/^[\w-]+$/.test(b);b=b.toUpperCase();return Da(a,function(a){return a.tagName==b})}function D(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Fa(a,b,c){var d=sa(a,b);if(d)return d;var e=w(a);return e.waitForBodyOpen().then(function(){var a=e.win;var b=e.win.document.head;if(b){var d=[];b=b.querySelectorAll("script[custom-element]");for(var k=0;k<b.length;k++)d.push(b[k].getAttribute("custom-element"))}else d=[];a=d.includes(c)?z(a,"extensions").waitForExtension(a,c):Promise.resolve();return a}).then(function(){var d=e.win;return d.ampExtendedElements&&d.ampExtendedElements[c]?va(x(a),b):null})};function E(a){return A(a,"resources")};var F,Ga="Webkit webkit Moz moz ms O o".split(" ");function Ha(a,b,c){var d;var e=a.style;if(!Ca(b,"--")){F||(F=B());var f=F[b];if(!f){f=b;if(void 0===e[b]){var g=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var h=0;h<Ga.length;h++){var k=Ga[h]+g;if(void 0!==e[k]){g=k;break b}}g=""}void 0!==e[g]&&(f=g)}F[b]=f}b=f}b&&(a.style[b]=d?c+d:c)}function Ia(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var G;function Ja(a,b,c){var d=void 0,e=a,f=c;var g=function(a){try{return f(a)}catch(y){throw self.reportError(y),y;}};var h=Ka(),k=!1;d&&(k=d.capture);e.addEventListener(b,g,h?d:k);return function(){e&&e.removeEventListener(b,g,h?d:k);g=e=f=null}}function Ka(){if(void 0!==G)return G;G=!1;try{var a={get capture(){G=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return G};function H(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a}function La(a,b,c){return Ja(a,b,c)}function Ma(a,b){var c=b,d=Ja(a,"mouseup",function(a){try{c(a)}finally{c=null,d()}});return d}function Na(a){var b,c,d=new Promise(function(b){c=Ma(a,b)});d.then(c,c);b&&b(c);return d};function Oa(a,b){function c(c){g=null;f=a.setTimeout(d,e);b.apply(null,c)}function d(){f=0;g&&c(g)}var e=100,f=0,g=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];f?g=b:c(b)}};function Pa(a){var b=a.getRootNode();this.Da=b.ownerDocument||b;this.j=this.Da.defaultView;this.oa=A(a,"viewport");this.S=[];this.S.push(La(b,"input",function(a){a=a.target;"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Qa(a)}));this.S.push(La(b,"mousedown",function(a){1==a.which&&(a=a.target,"TEXTAREA"==a.tagName&&Ra(a))}));var c=b.querySelectorAll("textarea");this.S.push(La(b,"amp:dom-update",function(){c=b.querySelectorAll("textarea")}));var d=Oa(this.j,function(a){a.relayoutAll&&Sa(c)});
this.S.push(this.oa.onResize(d));Ta(c)}function Ua(a){function b(){var b=c.querySelector("textarea[autoexpand]");b&&!d?d=new Pa(a):!b&&d&&(d.dispose(),d=null)}var c=a.getRootNode(),d=null;Ja(c,"amp:dom-update",b);b()}Pa.prototype.dispose=function(){this.S.forEach(function(a){return a()})};
function Ta(a){Promise.all(pa(a).map(function(a){return Va(a).then(function(b){b&&(r().warn("AMP-FORM",'"textarea[autoexpand]" with initially scrolling content will not autoexpand.\nSee https://github.com/ampproject/amphtml/issues/20839'),a.removeAttribute("autoexpand"))})}))}function Va(a){var b=E(a);return b.measureElement(function(){return a.scrollHeight>a.clientHeight})}function Sa(a){D(a,function(a){"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Qa(a)})}
function Ra(a){var b=E(a);Promise.all([b.measureElement(function(){return a.scrollHeight}),Na(a)]).then(function(c){var d=c[0],e=0;return b.measureMutateElement(a,function(){e=a.scrollHeight},function(){d!=e&&a.removeAttribute("autoexpand")})})}
function Qa(a){var b=E(a),c=a.ownerDocument.defaultView,d=0,e=0,f=0,g=Wa(a);b.measureMutateElement(a,function(){var b=c.getComputedStyle(a)||B();e=a.scrollHeight;var k=parseInt(b.getPropertyValue("max-height"),10);f=isNaN(k)?Infinity:k;d="content-box"==b.getPropertyValue("box-sizing")?-parseInt(b.getPropertyValue("padding-top"),10)+-parseInt(b.getPropertyValue("padding-bottom"),10):parseInt(b.getPropertyValue("border-top-width"),10)+parseInt(b.getPropertyValue("border-bottom-width"),10)},function(){return g.then(function(b){a.classList.toggle("i-amphtml-textarea-max",
b+d>f);var c="iAmphtmlHasExpanded"in a.dataset,g=c||e<=b;g&&(a.dataset.iAmphtmlHasExpanded="",Ha(a,"height",b+d+"px"))})})}
function Wa(a){var b=a.ownerDocument,c=b.defaultView,d=b.body,e=E(a),f=a.cloneNode(!1);f.classList.add("i-amphtml-textarea-clone");var g=0,h=0,k=!1;return e.measureMutateElement(d,function(){var b=c.getComputedStyle(a)||B(),d=parseInt(b.getPropertyValue("max-height"),10);g=parseInt(b.getPropertyValue("width"),10);k=isNaN(d)||a.scrollHeight<d},function(){k&&(a.scrollTop=0);Ha(f,"width",g+"px");b.body.appendChild(f)}).then(function(){return e.measureMutateElement(d,function(){h=f.scrollHeight},function(){var a=
f;a.parentElement&&a.parentElement.removeChild(a)})}).then(function(){return h})};function I(a){for(var b=a.elements,c={},d=/^(?:input|select|textarea)$/i,e=/^(?:submit|button|image|file|reset)$/i,f=/^(?:checkbox|radio)$/i,g={},h=0;h<b.length;g={F:g.F},h++){var k=b[h],m=k,y=m.checked;g.F=m.name;var Qb=m.multiple,Rb=m.options,Sb=m.tagName,Ya=m.type;m=m.value;!g.F||Xa(k)||!d.test(Sb)||e.test(Ya)||f.test(Ya)&&!y||(void 0===c[g.F]&&(c[g.F]=[]),Qb?D(Rb,function(a){return function(b){b.selected&&c[a.F].push(b.value)}}(g)):c[g.F].push(m))}var O=Za(a);O&&O.name&&(a=O.name,void 0===c[a]&&
(c[a]=[]),c[O.name].push(O.value));Object.keys(c).forEach(function(a){0==c[a].length&&delete c[a]});return c}function Za(a){var b=a.elements,c=b.length,d=a.ownerDocument.activeElement,e=null;for(a=0;a<c;a++){var f=b[a],g=f.type;if("BUTTON"==f.tagName||"submit"==g)if(e||(e=f),d==f)return d}return e}function Xa(a){if(a.disabled)return!0;a=Ea(a);for(var b=0;b<a.length;b++)if(a[b].disabled)return!0;return!1}
function $a(a){switch(a.type){case "select-multiple":case "select-one":a=a.options;for(var b=0;b<a.length;b++)if(a[b].selected!==a[b].defaultSelected)return!1;break;case "checkbox":case "radio":return a.checked===a.defaultChecked;default:return a.value===a.defaultValue}return!0};function ab(a,b){return a.hasAttribute("verify-xhr")?new bb(a,b):new cb(a)}function J(a){this.h=a}J.prototype.onCommit=function(){db(this);a:{var a=this.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled&&!$a(c)){a=!0;break a}}a=!1}return a?this.xa():Promise.resolve({updatedElements:[],errors:[]})};J.prototype.xa=function(){return Promise.resolve({updatedElements:[],errors:[]})};function db(a){(a=a.h.elements)&&D(a,function(a){a.setCustomValidity("")})}
function cb(){J.apply(this,arguments)}n(cb,J);function bb(a,b){this.h=a;this.$=b;this.U=null;this.ra=[]}n(bb,J);bb.prototype.xa=function(){var a=this,b=this.$().then(function(){return[]},function(a){return eb(a)});return fb(this,b).then(function(b){return gb(a,b)})};function fb(a,b){if(!a.U){a.U=new ja;var c=function(){return a.U=null};a.U.then(c,c)}return a.U.add(b)}
function gb(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.ra;a.ra=b;for(var f=0;f<b.length;f++){var g=b[f],h=r().assertString(g.name,"Verification errors must have a name property");g=r().assertString(g.message,"Verification errors must have a message property");h=r().assertElement(a.h.querySelector('[name="'+h+'"]'),"Verification error name property must match a field name");h.checkValidity()&&(h.setCustomValidity(g),d.push(h))}var k=e.filter(c).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:d.concat(k),errors:b}}function eb(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function hb(a,b){var c=z(a,"platform");return c.isIos()&&11==c.getMajorVersion()?new ib(b):FormData.prototype.entries&&FormData.prototype.delete?new K(b):new L(b)}function L(a){this.C=a?I(a):B()}L.prototype.append=function(a,b){var c=String(a);this.C[c]=this.C[c]||[];this.C[c].push(String(b))};L.prototype.delete=function(a){delete this.C[a]};
L.prototype.entries=function(){var a=this,b=[];Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.push([c,a])})});var c=0;return{next:function(){return c<b.length?{value:b[c++],done:!1}:{value:void 0,done:!0}}}};L.prototype.getFormData=function(){var a=this,b=new FormData;Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.append(c,a)})});return b};function K(a){this.D=new FormData(a);a&&(a=Za(a))&&this.append(a.name,a.value)}
K.prototype.append=function(a,b){this.D.append(a,b)};K.prototype.delete=function(a){this.D.delete(a)};K.prototype.entries=function(){return this.D.entries()};K.prototype.getFormData=function(){return this.D};function ib(a){K.call(this,a);var b=this;a&&D(a.elements,function(a){"file"==a.type&&0==a.files.length&&(b.D.delete(a.name),b.D.append(a.name,new Blob([]),""))})}n(ib,K);
ib.prototype.append=function(a,b,c){b&&"object"==typeof b&&""==b.name&&0==b.size?this.D.append(a,new Blob([]),c||""):this.D.append(a,b)};var jb={text:!0,textarea:!0};function kb(a,b){this.h=a;this.j=b;this.P=0;this.K=B();this.na=null;this.ba=!1;this.la()}l=kb.prototype;l.onSubmitting=function(){this.ba=!0;M(this)};l.onSubmitError=function(){this.ba=!1;M(this)};l.onSubmitSuccess=function(){this.ba=!1;this.na=hb(this.j,this.h).getFormData();this.K=B();this.P=0;M(this)};function M(a){var b=0<a.P&&!a.ba;a.h.classList.toggle("amp-form-dirty",b)}
l.la=function(){this.h.addEventListener("input",this.Fa.bind(this));this.h.addEventListener("reset",this.Ga.bind(this))};
l.Fa=function(a){a=a.target;var b=a.hidden;if(jb[a.type]&&a.name&&!b&&!Xa(a)){a:switch(a.tagName){case "INPUT":b="checkbox"==a.type||"radio"==a.type?!a.checked:!a.value;break a;case "TEXTAREA":b=!a.value;break a;case "SELECT":b=!1;break a;default:throw Error("isFieldEmpty: "+a.tagName+" is not a supported field element.");}(b=b||$a(a))||(this.na?(b=a.value,b=this.na.get(a.name)===b):b=!1);b?(a=a.name,this.K[a]&&(this.K[a]=!1,--this.P)):(a=a.name,this.K[a]||(this.K[a]=!0,++this.P))}M(this)};
l.Ga=function(){this.K=B();this.P=0;M(this)};function lb(){this.o=null}l=lb.prototype;l.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};l.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};l.removeAll=function(){this.o&&(this.o.length=0)};l.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};l.getHandlerCount=function(){return this.o?this.o.length:0};function mb(){this.qa=new lb}mb.prototype.beforeSubmit=function(a){return this.qa.add(a)};mb.prototype.fire=function(a){this.qa.fire(a)};function N(){var a=100;this.Ca=a;this.fa=this.ma=0;this.Y=Object.create(null)}N.prototype.has=function(a){return!!this.Y[a]};N.prototype.get=function(a){var b=this.Y[a];if(b)return b.access=++this.fa,b.payload};N.prototype.put=function(a,b){this.has(a)||this.ma++;this.Y[a]={payload:b,access:this.fa};if(!(this.ma<=this.Ca)){qa().warn("lru-cache","Trimming LRU cache");a=this.Y;var c=this.fa+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ma--)}};var P=self.AMP_CONFIG||{},nb={thirdParty:P.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:P.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof P.thirdPartyFrameRegex?new RegExp(P.thirdPartyFrameRegex):P.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:P.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof P.cdnProxyRegex?new RegExp(P.cdnProxyRegex):P.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:P.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:P.localDev||!1};var ob=C({c:!0,v:!0,a:!0,ad:!0,action:!0}),pb,qb,rb=/[?&]amp_js[^&]*/,sb=/[?&]amp_gsa[^&]*/,tb=/[?&]amp_r[^&]*/,ub=/[?&]amp_kit[^&]*/,vb=/[?&]usqp[^&]*/;
function Q(a){var b;pb||(pb=self.document.createElement("a"),qb=self.UrlCache||(self.UrlCache=new N));var c=b?null:qb,d=pb;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;d=p().test&&Object.freeze?Object.freeze(e):e;c&&c.put(a,d);a=d}return a}function wb(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function xb(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")};var yb=["GET","POST"];function zb(a){var b=a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?Fa(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){t(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function Ab(a,b){var c="amp-form";this.L=a;this.A=b;this.Ja=c}Ab.prototype.isSupported=function(){var a=this.L.ampdoc;return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.L.hasCapability("viewerRenderTemplate"):!1};Ab.prototype.fetchAndRenderTemplate=function(a,b,c,d){c=void 0===c?null:c;d=void 0===d?{}:d;var e;c||(e=this.A.maybeFindTemplate(a));return this.L.sendMessageAwaitResponse("viewerRenderTemplate",Bb(this,b,e,c,d))};
Ab.prototype.renderTemplate=function(a,b){if(this.isSupported()){t("string"===typeof b.html,"Server side html response must be defined");var c=this.A.findAndSetHtmlForTemplate(a,b.html)}else c=Array.isArray(b)?this.A.findAndRenderTemplateArray(a,b):this.A.findAndRenderTemplate(a,b);return c};
function Bb(a,b,c,d,e){e=void 0===e?{}:e;var f=C({type:a.Ja}),g="successTemplate",h=d&&d[g]?d[g]:c;h&&(f[g]={type:"amp-mustache",payload:h.innerHTML});var k="errorTemplate",m=d&&d[k]?d[k]:null;m&&(f[k]={type:"amp-mustache",payload:m.innerHTML});e&&Object.assign(f,e);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);
b.body=d}return C({originalRequest:{input:a,init:b},ampComponent:f})};function Cb(a,b){this.ka=b;this.oa=A(a,"viewport");this.ya=z(a.win,"vsync");this.ia=null;this.ha="";this.ca=!1;this.J=a.win.document.createElement("div");Ia(this.J,!1);this.J.classList.add("i-amphtml-validation-bubble");this.J.__BUBBLE_OBJ=this;a.getBody().appendChild(this.J)}Cb.prototype.isActiveOn=function(a){return this.ca&&a==this.ia};Cb.prototype.hide=function(){this.ca&&(this.ca=!1,this.ia=null,this.ha="",this.ya.run({measure:void 0,mutate:Db},{bubbleElement:this.J}))};
Cb.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.ha){this.ca=!0;this.ia=a;this.ha=b;var c={message:b,targetElement:a,bubbleElement:this.J,viewport:this.oa,id:this.ka};this.ya.run({measure:Eb,mutate:Fb},c)}};function Db(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);Ia(a.bubbleElement,!1)}function Eb(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Fb(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);Ia(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a)Ha(b,
d,a[d])};var Gb,Hb,Ib=0;function R(a){this.form=a;this.ampdoc=w(a);this.resources=E(a);this.root=this.ampdoc.getRootNode();this.aa=null}l=R.prototype;l.report=function(){};l.onBlur=function(){};l.onInput=function(){};l.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};
l.checkInputValidity=function(a){if("TEXTAREA"===a.tagName&&a.hasAttribute("pattern")&&(a.checkValidity()||"Please match the requested format."===a.validationMessage)){var b=a.getAttribute("pattern"),c=new RegExp("^"+b+"$","m"),d=c.test(a.value);a.setCustomValidity(d?"":"Please match the requested format.")}return a.checkValidity()};l.checkFormValidity=function(a){Jb(this,a);return a.checkValidity()};l.reportFormValidity=function(a){Jb(this,a);return a.reportValidity()};
function Jb(a,b){D(b.elements,function(b){"TEXTAREA"==b.tagName&&a.checkInputValidity(b)})}l.fireValidityEventIfNecessary=function(){var a=this.aa;this.aa=this.checkFormValidity(this.form);if(a!==this.aa){var b=H(this.form.ownerDocument.defaultView,this.aa?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Kb(){R.apply(this,arguments)}n(Kb,R);Kb.prototype.report=function(){this.reportFormValidity(this.form);this.fireValidityEventIfNecessary()};
function S(a){R.call(this,a);var b="i-amphtml-validation-bubble-"+Ib++;this.T=new Cb(this.ampdoc,b)}n(S,R);S.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){a[b].focus();this.T.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};S.prototype.onBlur=function(a){"submit"!=a.target.type&&this.T.hide()};
S.prototype.onInput=function(a){a=a.target;this.T.isActiveOn(a)&&(this.checkInputValidity(a)?(a.removeAttribute("aria-invalid"),this.T.hide()):(a.setAttribute("aria-invalid","true"),this.T.show(a,a.validationMessage)))};function T(a){R.call(this,a)}n(T,R);l=T.prototype;l.reportInput=function(a){var b=Lb(a);b&&this.showValidationFor(a,b)};l.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
l.getValidationFor=function(a,b){if(!a.id)return null;"TEXTAREA"===a.tagName&&(b="patternMismatch");var c="__AMP_VALIDATION_"+b;c in a||(a[c]=this.root.querySelector("[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]")));return a[c]};
l.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.__AMP_VISIBLE_VALIDATION=c,this.resources.mutateElement(a,function(){return a.setAttribute("aria-invalid","true")}),this.resources.mutateElement(c,function(){return c.classList.add("visible")}))};
l.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,this.resources.mutateElement(a,function(){return a.removeAttribute("aria-invalid")}),this.resources.mutateElement(b,function(){return b.classList.remove("visible")}))};l.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};l.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
l.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!this.checkInputValidity(a)&&this.reportInput(a)};l.onBlur=function(a){this.onInteraction(a)};l.onInput=function(a){this.onInteraction(a)};function Mb(){T.apply(this,arguments)}n(Mb,T);Mb.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
Mb.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(){T.apply(this,arguments)}n(U,T);U.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)this.checkInputValidity(b[c])||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};U.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Nb(){T.apply(this,arguments)}n(Nb,T);
Nb.prototype.shouldValidateOnInteraction=function(){return!0};Nb.prototype.onInteraction=function(a){T.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function Ob(){U.apply(this,arguments)}n(Ob,U);Ob.prototype.shouldValidateOnInteraction=function(){return!0};Ob.prototype.onInteraction=function(a){U.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function Pb(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new Nb(a);case "show-all-on-submit":return new U(a);case "interact-and-submit":return new Ob(a);case "show-first-on-submit":return new Mb(a)}a.ownerDocument&&void 0===Gb&&(Gb=!!document.createElement("form").reportValidity);return Gb?new Kb(a):new S(a)}
function Lb(a){var b=["badInput"];for(c in a.validity)b.includes(c)||b.push(c);var c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};function Tb(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Ub(b));var c=b.FormProxy,d=new c(a);"action"in d||Vb(a,d);a.$p=d}
function Ub(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype,f=[a.HTMLFormElement,a.EventTarget],g=f.reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]);g.forEach(function(b){var d={},f;for(f in b){d.w=a.Object.getOwnPropertyDescriptor(b,f);if(d.w&&f.toUpperCase()!=f&&!Ca(f,"on")&&!e.hasOwnProperty.call(c,f))if("function"==typeof d.w.value)d.ea=d.w.value,c[f]=function(a){return function(){return a.ea.apply(this.h,
arguments)}}(d);else{var g={};d.w.get&&(g.get=function(a){return function(){return a.w.get.call(this.h)}}(d));d.w.set&&(g.set=function(a){return function(b){return a.w.set.call(this.h,b)}}(d));a.Object.defineProperty(c,f,g)}d={ea:d.ea,w:d.w}}});return b}
function Vb(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c){d.l=e;if(!(d.l in b||d.l.toUpperCase()==d.l||Ca(d.l,"on"))){d.m=Wb[d.l];var f=a[d.l];if(d.m)if(d.m.access==V){d.N=void 0;if(f&&f.nodeType){var g=c=f,h=g.nextSibling;g=g.parentNode;g.removeChild(c);try{d.N=a[d.l]}finally{g.insertBefore(c,h)}}else d.N=f;Object.defineProperty(b,d.l,{get:function(a){return function(){return a.N}}(d)})}else d.m.access==W&&(d.O=d.m.attr||d.l,Object.defineProperty(b,
d.l,{get:function(c){return function(){var d=b.getAttribute(c.O);return null==d&&void 0!==c.m.def?c.m.def:c.m.type==Xb?"true"===d:c.m.type==Yb?null!=d:c.m.type==Zb?(d=d||"",u(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.m.type==Yb&&(c=c?"":null);null!=c?b.setAttribute(a.O,c):b.removeAttribute(a.O)}}(d)}));else Object.defineProperty(b,d.l,{get:function(b){return function(){return a[b.l]}}(d),set:function(b){return function(c){a[b.l]=c}}(d)})}d={N:d.N,O:d.O,m:d.m,l:d.l}}}
var W=1,V=2,Zb=1,Xb=2,Yb=3,Wb={acceptCharset:{access:W,attr:"accept-charset"},accessKey:{access:W,attr:"accesskey"},action:{access:W,type:Zb},attributes:{access:V},autocomplete:{access:W,def:"on"},children:{access:V},dataset:{access:V},dir:{access:W},draggable:{access:W,type:Xb,def:!1},elements:{access:V},encoding:{access:V},enctype:{access:W},hidden:{access:W,type:Yb,def:!1},id:{access:W,def:""},lang:{access:W},localName:{access:V},method:{access:W,def:"get"},name:{access:W},noValidate:{access:W,
attr:"novalidate",type:Yb,def:!1},prefix:{access:V},spellcheck:{access:W},style:{access:V},target:{access:W,def:""},title:{access:W},translate:{access:W}};function $b(a,b){var c='form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/',
d=!1,e="amp-form",f=a.getHeadNode(),g=ac(f,bc(f,c),d||!1,e||null);if(b){var h=a.getRootNode();if(cc(h,g))b(g);else var k=setInterval(function(){cc(h,g)&&(clearInterval(k),b(g))},4)}}
function ac(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=B());var f=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,g=c?"amp-runtime":f?"amp-extension="+d:null;if(g){var h=dc(a,e,g);if(h)return h.textContent!==b&&(h.textContent=b),h}var k=(a.ownerDocument||a).createElement("style");k.textContent=b;var m=null;c?k.setAttribute("amp-runtime",""):f?(k.setAttribute("amp-extension",d||""),m=dc(a,e,"amp-runtime")):(d&&k.setAttribute(d,""),m=a.lastChild);b=m;a.insertBefore(k,b?b.nextSibling:a.firstChild);
g&&(e[g]=k);return k}function dc(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function bc(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function cc(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function ec(a,b,c){Fa(a,"amp-analytics-instrumentation","amp-analytics").then(function(d){d&&d.triggerEventForTarget(a,b,c)})};var fc=["amp-selector"];
function gc(a,b){var c=this;try{Tb(a)}catch(f){qa().error("amp-form","form proxy failed to install",f)}a.__AMP_FORM=this;this.ka=b;this.j=a.ownerDocument.defaultView;this.La=z(this.j,"timer");this.wa=u(a,"url-replace");this.ja=null;this.h=a;this.A=z(this.j,"templates");this.Oa=z(this.j,"xhr");this.X=u(this.h,"action");this.ua=E(this.h);this.L=A(this.h,"viewer");this.R=new Ab(this.L,this.A);this.H=(this.h.getAttribute("method")||"GET").toUpperCase();this.Ka=this.h.getAttribute("target");this.M=hc(this,
"action-xhr");this.Na=hc(this,"verify-xhr");this.va=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.va||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");this.I="initial";b=this.h.elements;for(var d=0;d<b.length;d++){var e=b[d].name;t("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,b[d])}this.Z=new kb(this.h,this.j);this.da=Pb(this.h);this.Ma=ab(this.h,function(){return ic(c)});this.X.installActionHandler(this.h,
this.Ba.bind(this));this.la();jc(this);this.pa=this.ta=this.Aa=null;va(x(a),"form-submit-service").then(function(a){c.pa=a})}function hc(a,b){var c=a.h.getAttribute(b);if(c){var d=u(a.h,"url");d.assertHttpsUrl(c,a.h,b);t(!d.isProxyOrigin(c),"form %s should not be on AMP CDN: %s",b,a.h)}return c}l=gc.prototype;
l.requestForFormFetch=function(a,b,c,d){var e="GET"==b||"HEAD"==b;if(e){kc(this);var f=I(this.h);d&&d.forEach(function(a){delete f[a]});c&&Ba(f,c);var g=wb(a,xb(f))}else{g=a;var h=hb(this.j,this.h);d&&d.forEach(function(a){h.delete(a)});for(var k in c)h.append(k,c[k])}var m={xhrUrl:g,fetchOpt:C({body:h,method:b,credentials:"include",headers:C({Accept:"application/json"})})};return zb(this.h).then(function(a){a&&(t("POST"==m.fetchOpt.method,"Cannot attach auth token with GET request."),h.append("ampViewerAuthToken",
a));return m})};l.setXhrAction=function(a){this.M=a};l.Ba=function(a){var b=this;if(!a.satisfiesTrust(100))return null;if("submit"==a.method)return lc(this).then(function(){var c=a;return"submitting"!=b.I&&mc(b)?nc(b,c.trust,null):Promise.resolve(null)});"clear"===a.method&&oc(this);return null};function lc(a){if(a.ja)return a.ja;var b=a.h.querySelectorAll(fc.join(",")),c=pa(b).map(function(a){return a.whenBuilt()});return a.ja=pc(a,c,2E3)}
l.la=function(){var a=this;this.L.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});this.h.addEventListener("submit",this.Ea.bind(this),!0);this.h.addEventListener("blur",function(b){qc(b.target);a.da.onBlur(b)},!0);this.R.isSupported()||this.h.addEventListener("change",function(b){a.Ma.onCommit().then(function(c){var d=c.updatedElements,e=c.errors;d.forEach(qc);a.da.onBlur(b);"verifying"===a.I&&(e.length?(X(a,"verify-error"),Y(a,C({verifyErrors:e})).then(function(){rc(a,
"verify-error",e)})):X(a,"initial"))})});this.h.addEventListener("input",function(b){qc(b.target);a.da.onInput(b)})};function jc(a){Fa(a.h,"inputmask","amp-inputmask").then(function(a){a&&a.install()})}function sc(a,b){tc(a,"Form analytics not supported");var c=C({}),d=I(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;ec(a.h,b,c)}
function oc(a){a.h.reset();X(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");D(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");D(c,function(a){a.classList.remove("visible")});uc(a.h)}
l.Ea=function(a){if("submitting"==this.I||!mc(this))return a.stopImmediatePropagation(),a.preventDefault(),Promise.resolve(null);(this.M||"POST"==this.H)&&a.preventDefault();return nc(this,100,a)};
function nc(a,b,c){try{var d={form:a.h,actionXhrMutator:a.setXhrAction.bind(a)};a.pa.fire(d)}catch(k){qa().error("amp-form","Form submit service failed: %s",k)}var e=vc(a),f=a.h.getElementsByClassName("i-amphtml-async-input");a.Z.onSubmitting();if(!a.M&&"GET"==a.H){tc(a,"Non-XHR GETs not supported.");kc(a);if(0===f.length){for(d=0;d<e.length;d++)a.wa.expandInputValueSync(e[d]);var g=!c;wc(a,g);a.Z.onSubmitSuccess();return Promise.resolve()}c&&c.preventDefault()}X(a,"submitting");var h=[];h.push(xc(a,
e));D(f,function(b){h.push(yc(a,b))});return pc(a,h,1E4).then(function(){if(a.M)var c=zc(a,b);else"POST"==a.H?t(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h):"GET"==a.H&&wc(a,!0),c=Promise.resolve();return c},function(b){var c={};b&&b.message&&(c.error=b.message);return Ac(a,b,c)})}function vc(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}
function ic(a){if("submitting"===a.I)return Promise.resolve();X(a,"verifying");rc(a,"verify",null);return xc(a,vc(a)).then(function(){return Bc(a)})}function zc(a,b){a.R.isSupported()?b=Cc(a,b):(Dc(a,b),b=a.$(a.M,a.H).then(function(b){return Ec(a,b)},function(b){return Fc(a,b)}));p().test&&(a.Aa=b);return b}
function Cc(a,b){var c,d=I(a.h);return Y(a,d).then(function(){return a.X.trigger(a.h,"submit",null,b)}).then(function(){return a.requestForFormFetch(a.M,a.H)}).then(function(b){var d=c=b,e=c.fetchOpt||{};var h=e.method;void 0===h?h="GET":(h=h.toUpperCase(),yb.includes(h));e.method=h;e.headers=e.headers||C({});d.fetchOpt=e;d=c;h=c.xhrUrl;e=(e=c.fetchOpt)||{};var k=a.j;k=k.origin||Q(k.location.href).origin;h=Q(h).origin;k==h&&(e.headers=e.headers||{},e.headers["AMP-Same-Origin"]="true");d.fetchOpt=
e;d=c;e=c.xhrUrl;if(!1!==c.fetchOpt.ampCors){h=a.j;k=Q(e);k=ma(k.search);t(!("__amp_source_origin"in k),"Source origin is not allowed in %s",e);h=h.location.href;"string"==typeof h&&(h=Q(h));k=h;"string"==typeof k&&(k=Q(k));if(nb.cdnProxyRegex.test(k.origin)){k=h.pathname.split("/");t(ob[k[1]],"Unknown path prefix in url %s",h.href);var m=k[2],y="s"==m?"https://"+decodeURIComponent(k[3]):"http://"+decodeURIComponent(m);t(0<y.indexOf("."),"Expected a . in origin %s",y);k.splice(1,"s"==m?3:2);k=y+k.join("/");
m=(m=h.search)&&"?"!=m?(m=m.replace(rb,"").replace(sb,"").replace(tb,"").replace(ub,"").replace(vb,"").replace(/^[?&]/,""))?"?"+m:"":"";h=k+m+(h.hash||"")}else h=h.href;h=Q(h).origin;h=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(h);e=wb(e,h,void 0)}d.xhrUrl=e;return a.R.fetchAndRenderTemplate(a.h,c,Gc(a))}).then(function(b){return Hc(a,b)},function(b){var c={};b&&b.message&&(c.error=b.message);return Ac(a,b,c)})}
function Gc(a){var b,c=a.h.querySelector("[submit-success]");c&&(b=a.A.maybeFindTemplate(c));var d,e=a.h.querySelector("[submit-error]");e&&(d=a.A.maybeFindTemplate(e));return{successTemplate:b,errorTemplate:d}}function Hc(a,b){return Ic(a,ia(function(){return b}))}function Dc(a,b){sc(a,"amp-form-submit");var c=I(a.h);Y(a,c).then(function(){a.X.trigger(a.h,"submit",null,b)})}function xc(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.wa.expandInputValueAsync(b[d]));return pc(a,c,100)}
function yc(a,b){return b.getImpl().then(function(a){return a.getValue()}).then(function(c){var d=b.getAttribute("name");d=a.h.querySelector("input[name="+String(d).replace(xa,ya)+"]");if(!d){d=C({name:b.getAttribute("name"),hidden:"true"});var e=a.j.document.createElement("input"),f;for(f in d)e.setAttribute(f,d[f]);d=e}d.setAttribute("value",c);a.h.appendChild(d)})}
function Bc(a){var b=pa(a.h.querySelectorAll("["+"no-verify".replace(xa,ya)+"]")),c=b.map(function(a){return a.name||a.id}),d={};return a.$(a.Na,a.H,(d.__amp_form_verify=!0,d),c)}l.$=function(a,b,c,d){var e=this;tc(this,"XHRs should be proxied.");return this.requestForFormFetch(a,b,c,d).then(function(a){return e.Oa.fetch(a.xhrUrl,a.fetchOpt)})};function Ec(a,b){var c=b.json();return Ic(a,c).then(function(){sc(a,"amp-form-submit-success");Jc(a,b)})}
function Ic(a,b){return b.then(function(b){X(a,"submit-success");Y(a,b||{}).then(function(){rc(a,"submit-success",b);a.Z.onSubmitSuccess()})},function(a){r().error("amp-form","Failed to parse response JSON: %s",a)})}function Fc(a,b){return(b&&b.response?b.response.json().catch(function(){return null}):Promise.resolve(null)).then(function(c){sc(a,"amp-form-submit-error");Ac(a,b,c);Jc(a,b.response)})}
function Ac(a,b,c){X(a,"submit-error");r().error("amp-form","Form submission failed: %s",b);return ia(function(){Y(a,c).then(function(){rc(a,"submit-error",c);a.Z.onSubmitError()})})}function wc(a,b){sc(a,"amp-form-submit");b&&a.h.submit();X(a,"initial")}function tc(a,b){var c=a.R.isSupported();t(!1===c,"[amp-form]: viewerRenderTemplate | %s",b)}
function kc(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");t(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function mc(a){void 0===Hb&&(Hb=!!a.j.document.createElement("input").checkValidity);if(Hb){var b=Kc(a.h);if(a.va)return a.da.report(),b}return!0}
function Jc(a,b){tc(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){t("_blank"!=a.Ka,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=u(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){t(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",c)}A(a.h,"navigation").navigateTo(a.j,c,"AMP-Redirect-To")}}}
function rc(a,b,c){c=H(a.j,"amp-form."+b,C({response:c}));a.X.trigger(a.h,b,c,100)}function pc(a,b,c){return Promise.race([Promise.all(b),a.La.promise(c)])}
function X(a,b){var c=a.I;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);var d=a.h.querySelector("["+c+"]");if(d){/^[\w-]+$/.test("i-amphtml-rendered");if(void 0!==za)var e=za;else{try{var f=d.ownerDocument,g=f.createElement("div"),h=f.createElement("div");g.appendChild(h);e=g.querySelector(":scope div")===h}catch(k){e=!1}e=za=e}e?d=d.querySelector("> [i-amphtml-rendered]".replace(/^|,/g,"$&:scope ")):(d.classList.add("i-amphtml-scoped"),e="> [i-amphtml-rendered]".replace(/^|,/g,
"$&.i-amphtml-scoped "),e=d.querySelectorAll(e),d.classList.remove("i-amphtml-scoped"),d=void 0===e[0]?null:e[0]);d&&d.parentElement&&d.parentElement.removeChild(d)}a.I=b}
function Y(a,b){var c=a.h.querySelector("["+a.I+"]"),d=Promise.resolve();if(c){var e="rendered-message-"+a.ka;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.A.hasTemplate(c)?d=a.R.renderTemplate(c,b).then(function(b){b.id=e;b.setAttribute("i-amphtml-rendered","");return a.ua.mutateElement(c,function(){c.appendChild(b);var d=H(a.j,"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(d)})}):a.ua.mutateElement(c,function(){})}p().test&&(a.ta=
d);return d}l.Pa=function(){return this.ta};l.Ra=function(){return this.Aa};function Kc(a){var b=a.querySelectorAll("input,select,textarea,fieldset");D(b,function(a){return Z(a)});return Z(a)}function uc(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.W=d;var e=a.querySelectorAll("."+String(c.W).replace(xa,ya));D(e,function(a){return function(b){b.classList.remove(a.W)}}(c));c={W:c.W}}}
function Z(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var f in a.validity)a.classList.toggle(f,a.validity[f]);if(b&&c){f=Ea(a);for(var g=0;g<f.length;g++)Z(f[g]);
a.form&&Z(a.form)}return e}function qc(a){Z(a,!0)}function Lc(a){this.za=Mc(a).then(function(){return Nc(a)});p().test&&this.za.then(function(){var b=a.win,c=H(b,"amp:form-service:initialize",null,{bubbles:!0});b.dispatchEvent(c)})}Lc.prototype.whenInitialized=function(){return this.za};function Mc(a){var b=new ha;$b(a,b.resolve);return b.promise}function Nc(a){return a.whenReady().then(function(){var b=a.getRootNode();Oc(b.querySelectorAll("form"));Ua(a);Pc(b)})}
function Oc(a){a&&D(a,function(a,c){var b=a.__AMP_FORM||null;b||new gc(a,"amp-form-"+c)})}function Pc(a){a.addEventListener("amp:dom-update",function(){Oc(a.querySelectorAll("form"))})}(function(a){a.registerServiceForDoc("form-submit-service",mb);a.registerServiceForDoc("amp-form",Lc)})(self.AMP);
})});

//# sourceMappingURL=amp-form-0.1.js.map
